services:
    web:
        build: .
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=production
            - NEXT_TELEMETRY_DISABLED=1
        volumes:
            - ./.next/cache:/app/.next/cache
        restart: unless-stopped
